user:
    resource: "@UserBundle/Resources/config/routing.xml"
    prefix:   /

biblioteca:
    resource: "@bibliotecaBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
