<?php

namespace bibliotecaBundle\Entity;

/**
 * AcervoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcervoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAtivo(){

        return $this->findBy(
        [
            'ativo' => 1
        ],
        [
            'id' => 'DESC'
        ]
        );

    }

    public function Inativar($id){

        $repository = $this->_em->getRepository(Acervo::class);
        $acervo = $repository->findOneBy($id);
        
        $acervo->getId();
        $acervo->setAtivo(0);

        $this->_em->persist($acervo);
        $this->_em->flush();
    }

}
