<?php

namespace bibliotecaBundle\Entity;

/**
 * AcervoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcervoRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByAtivo(){

        return $this->findBy(
        [
            'ativo' => 1
        ],
        [
            'id' => 'DESC'
        ]
        );

    }

}
